# Generated by Django 5.1.5 on 2025-01-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('user_weight', models.FloatField()),
                ('user_height', models.FloatField()),
                ('target_weight', models.FloatField()),
                ('gender', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
