# Generated by Django 5.1.5 on 2025-03-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_food_id_food_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='customuser',
        ),
        migrations.AlterModelTable(
            name='food',
            table='food',
        ),
    ]
