# Generated by Django 5.1.5 on 2025-03-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_user_customuser_alter_food_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedFood',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=255)),
                ('calories_kcal', models.FloatField()),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'selectedfood',
            },
        ),
    ]
