services:
  - type: web
    name: django-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn calorietrackerproject.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: railway-mysql
          property: connectionString
