# Generated by Django 5.1.5 on 2025-02-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='id',
            new_name='food_id',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='name',
            new_name='food_name',
        ),
        migrations.RemoveField(
            model_name='food',
            name='calories',
        ),
        migrations.AddField(
            model_name='food',
            name='calories_kcal',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
