# Generated by Django 5.1.5 on 2025-02-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_id_food_food_id_rename_name_food_food_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='food',
            table='Food',
        ),
    ]
