# Generated by Django 5.1.5 on 2025-02-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_food_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food_id',
            new_name='id',
        ),
    ]
