# Generated by Django 5.1.5 on 2025-03-17 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_selectedfood_options_selectedfood_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='history',
            table='history',
        ),
    ]
